### ISSUE TITLE
CSS与数学的奥秘-clip-path

### ISSUE THREAD

**Issue by hubvue** [hubvue/nota#6]
### 你不知道的clip-path
在我们想要做网页上的一些特殊形状的时候，我们都知道可以用border-radius、border、box-shadow、outline、伪元素等等来去组合成各种形状，以达到自己想要的结果。这明显的弊端是增加了我们代码量的同时又增加了元素的数量。于是我们在致力于寻找用一行CSS代码就可以画出各种各样的图形的方案。终于，clip-path出现了。
#### clip-path
clip-path前身是[clip](https://www.w3cplus.com/css3/clip.html),今天主要总结一下clip-path。
#### 裁切路径和裁切区域
在clip-path上有两个非常重要的概念：裁切路径（Clipping Path）和裁切区域（Clipping Region）。这也正如clip-path单词所示，它的作用主要是依据所指定的路径进行裁切，而裁切区域就是我们要保留的区域。

如图所示：
![](https://www.w3cplus.com/sites/default/files/blogs/2016/1607/clip-path-2.png)

#### clip-path的语法
```css
clip-path: <clip-source> | [ <basic-shape> || <geometry-box> ] | none
```
默认值为none。
1. clip-source：可以是内、外部的SVG的<clipPath>元素的URL引用
2. basic-shape: 使用一些基本的形状函数创建的一个形状。主要包括circle()、ellipse()、inset()和polygon()。
3. geometry-box: 是可选参数。此参数和basic-shape函数一起使用时，可以为basic-shape的裁剪工作提供参考盒子。

#### clip-path的使用
```CSS
img { 
    clip-path: polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%); 
}
```
polygon函数作用是绘制多边形，以点连接成路径进行剪切（路径为点之间的顺时针连接）。
![](https://www.w3cplus.com/sites/default/files/blogs/2016/1607/clip-path-3.png)

#### 利用geometry-box来决定剪切方式
geometry-box可以是shape-box、fill、stroke或者view-box。其中shape-box应用于HTML元素，它具有四种值：margin-box、border-box、padding-box和content-box。

如图所示就是shape-box所取的值，表示剪切范围。
![](https://www.w3cplus.com/sites/default/files/blogs/2014/1408/reference-boxes-1.jpg)
```CSS
.clip-me { 
    clip-path: polygon(10% 20%, 20% 30%, 50% 80%) margin-box; 
    margin: 10%; 
    
}
```
在上例中，元素的 margin-box 会作为参考，来决定裁剪点的实际位置。点（10%，10%）是 margin-box 的左上角，所以 clip-path 的定位会根据此点进行计算。

### 自己计算裁切的五角星
[五角星](http://www.ctomorrow.top/task-demo/clipPath.html)
